// ─────────────────────────────────────────────────────────────────────────────
// Auto-generated by scripts/split-locales.js — DO NOT EDIT MANUALLY
// Re-run the script if you add or rename a namespace in locales/*.ts
// ─────────────────────────────────────────────────────────────────────────────

import ko_common from './locales/ko/common.json';
import ko_languages from './locales/ko/languages.json';
import ko_tabs from './locales/ko/tabs.json';
import ko_welcome from './locales/ko/welcome.json';
import ko_auth from './locales/ko/auth.json';
import ko_home from './locales/ko/home.json';
import ko_categories from './locales/ko/categories.json';
import ko_explore from './locales/ko/explore.json';
import ko_bookings from './locales/ko/bookings.json';
import ko_trips from './locales/ko/trips.json';
import ko_profile from './locales/ko/profile.json';
import ko_flights from './locales/ko/flights.json';
import ko_hotels from './locales/ko/hotels.json';
import ko_transport from './locales/ko/transport.json';
import ko_aiPlanner from './locales/ko/aiPlanner.json';
import ko_destination from './locales/ko/destination.json';
import ko_components from './locales/ko/components.json';

import en_common from './locales/en/common.json';
import en_languages from './locales/en/languages.json';
import en_tabs from './locales/en/tabs.json';
import en_welcome from './locales/en/welcome.json';
import en_auth from './locales/en/auth.json';
import en_home from './locales/en/home.json';
import en_categories from './locales/en/categories.json';
import en_explore from './locales/en/explore.json';
import en_bookings from './locales/en/bookings.json';
import en_trips from './locales/en/trips.json';
import en_profile from './locales/en/profile.json';
import en_flights from './locales/en/flights.json';
import en_hotels from './locales/en/hotels.json';
import en_transport from './locales/en/transport.json';
import en_aiPlanner from './locales/en/aiPlanner.json';
import en_destination from './locales/en/destination.json';
import en_components from './locales/en/components.json';

import vi_common from './locales/vi/common.json';
import vi_languages from './locales/vi/languages.json';
import vi_tabs from './locales/vi/tabs.json';
import vi_welcome from './locales/vi/welcome.json';
import vi_auth from './locales/vi/auth.json';
import vi_home from './locales/vi/home.json';
import vi_categories from './locales/vi/categories.json';
import vi_explore from './locales/vi/explore.json';
import vi_bookings from './locales/vi/bookings.json';
import vi_trips from './locales/vi/trips.json';
import vi_profile from './locales/vi/profile.json';
import vi_flights from './locales/vi/flights.json';
import vi_hotels from './locales/vi/hotels.json';
import vi_transport from './locales/vi/transport.json';
import vi_aiPlanner from './locales/vi/aiPlanner.json';
import vi_destination from './locales/vi/destination.json';
import vi_components from './locales/vi/components.json';

export type SupportedLocale = 'ko' | 'en' | 'vi';
export const supportedLocales: SupportedLocale[] = ['ko', 'en', 'vi'];
export const defaultLocale: SupportedLocale = 'ko';

/** All i18next namespace names (= top-level keys in locale objects) */
export type AppNamespace = 'common' | 'languages' | 'tabs' | 'welcome' | 'auth' | 'home' | 'categories' | 'explore' | 'bookings' | 'trips' | 'profile' | 'flights' | 'hotels' | 'transport' | 'aiPlanner' | 'destination' | 'components';

export const resources = {
  ko: {
    common: ko_common,
    languages: ko_languages,
    tabs: ko_tabs,
    welcome: ko_welcome,
    auth: ko_auth,
    home: ko_home,
    categories: ko_categories,
    explore: ko_explore,
    bookings: ko_bookings,
    trips: ko_trips,
    profile: ko_profile,
    flights: ko_flights,
    hotels: ko_hotels,
    transport: ko_transport,
    aiPlanner: ko_aiPlanner,
    destination: ko_destination,
    components: ko_components,
  },
  en: {
    common: en_common,
    languages: en_languages,
    tabs: en_tabs,
    welcome: en_welcome,
    auth: en_auth,
    home: en_home,
    categories: en_categories,
    explore: en_explore,
    bookings: en_bookings,
    trips: en_trips,
    profile: en_profile,
    flights: en_flights,
    hotels: en_hotels,
    transport: en_transport,
    aiPlanner: en_aiPlanner,
    destination: en_destination,
    components: en_components,
  },
  vi: {
    common: vi_common,
    languages: vi_languages,
    tabs: vi_tabs,
    welcome: vi_welcome,
    auth: vi_auth,
    home: vi_home,
    categories: vi_categories,
    explore: vi_explore,
    bookings: vi_bookings,
    trips: vi_trips,
    profile: vi_profile,
    flights: vi_flights,
    hotels: vi_hotels,
    transport: vi_transport,
    aiPlanner: vi_aiPlanner,
    destination: vi_destination,
    components: vi_components,
  },
} as const;
