/**
 * Migration script: splits monolithic locale TS files into per-namespace JSON files.
 *
 * Input:  locales/{ko,en,vi}.ts  (existing i18n-js format)
 * Output: src/i18n/locales/{ko,en,vi}/{namespace}.json  (one file per top-level key)
 *         src/i18n/resources.ts  (auto-generated typed import map)
 *
 * Run: node scripts/split-locales.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LOCALES_SRC = path.join(ROOT, 'locales');
const LOCALES_OUT = path.join(ROOT, 'src', 'i18n', 'locales');
const RESOURCES_OUT = path.join(ROOT, 'src', 'i18n', 'resources.ts');

const SUPPORTED_LOCALES = ['ko', 'en', 'vi'];

// ── Parse a TypeScript locale file ────────────────────────────────────────────
function parseTsLocale(filePath) {
  let src = fs.readFileSync(filePath, 'utf8');
  // Strip the "export default " prefix and trailing semicolon
  src = src.replace(/^export\s+default\s+/, '').trimEnd().replace(/;$/, '');
  // eslint-disable-next-line no-eval
  return eval('(' + src + ')');
}

// ── Main ──────────────────────────────────────────────────────────────────────
const localeDatas = {};

for (const lang of SUPPORTED_LOCALES) {
  const filePath = path.join(LOCALES_SRC, `${lang}.ts`);
  console.log(`Reading ${path.relative(ROOT, filePath)}`);
  localeDatas[lang] = parseTsLocale(filePath);
}

// Derive namespaces from the reference locale (ko)
const namespaces = Object.keys(localeDatas['ko']);
console.log(`\nFound ${namespaces.length} namespaces: ${namespaces.join(', ')}\n`);

// ── Write namespace JSON files ─────────────────────────────────────────────────
for (const lang of SUPPORTED_LOCALES) {
  const outDir = path.join(LOCALES_OUT, lang);
  fs.mkdirSync(outDir, { recursive: true });

  for (const ns of namespaces) {
    const data = localeDatas[lang][ns];
    if (data === undefined) {
      console.warn(`  [WARN] Namespace '${ns}' missing in locale '${lang}' — skipping`);
      continue;
    }
    const outFile = path.join(outDir, `${ns}.json`);
    fs.writeFileSync(outFile, JSON.stringify(data, null, 2) + '\n');
    console.log(`  Created: src/i18n/locales/${lang}/${ns}.json`);
  }
}

// ── Generate resources.ts ──────────────────────────────────────────────────────
const importLines = [];
for (const lang of SUPPORTED_LOCALES) {
  for (const ns of namespaces) {
    importLines.push(`import ${lang}_${ns} from './locales/${lang}/${ns}.json';`);
  }
  importLines.push(''); // blank line between locales
}

const buildLocale = (lang) =>
  `  ${lang}: {\n${namespaces.map((ns) => `    ${ns}: ${lang}_${ns},`).join('\n')}\n  },`;

const resourcesTs = `// ─────────────────────────────────────────────────────────────────────────────
// Auto-generated by scripts/split-locales.js — DO NOT EDIT MANUALLY
// Re-run the script if you add or rename a namespace in locales/*.ts
// ─────────────────────────────────────────────────────────────────────────────

${importLines.join('\n')}
export type SupportedLocale = 'ko' | 'en' | 'vi';
export const supportedLocales: SupportedLocale[] = ['ko', 'en', 'vi'];
export const defaultLocale: SupportedLocale = 'ko';

/** All i18next namespace names (= top-level keys in locale objects) */
export type AppNamespace = ${namespaces.map((ns) => `'${ns}'`).join(' | ')};

export const resources = {
${SUPPORTED_LOCALES.map(buildLocale).join('\n')}
} as const;
`;

// Ensure output directory exists (resources.ts lives at src/i18n/)
fs.mkdirSync(path.join(ROOT, 'src', 'i18n'), { recursive: true });
fs.writeFileSync(RESOURCES_OUT, resourcesTs);
console.log('\nCreated: src/i18n/resources.ts');
console.log('\n✓ Done. All locale namespace files written.');
